version: '3'

services:

  db:
    image: postgres:15.5-bullseye
    container_name: tct-32-db
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - tct-32-network

  app:
    build: 
      dockerfile: Dockerfile
    image: pongsakon/app:1.0.0
    container_name: tct-32-app
    ports:
      - 13377:1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL={DATABASE_SSL}
    networks:
      - tct-32-network
    depends_on:
      - db

networks:
  tct-32-network:
